### ISSUE TITLE
Kernel 3.5.0 Docs Work

### ISSUE THREAD

**Issue by WillXuCodes** [purduesigbots/pros-docs#236]
### TODO List for Kernel 3.5.0 Changes:

- [x] New Screen C/C++ API 
- [x] Update to reset function blocking nature (it now blocks for approximately 12 milliseconds until the flag is set correctly) 
- [x] Document new exposed to user registry functions from [here](https://github.com/purduesigbots/pros/pull/282/files) 
- [x] Update registry_bind_port, and registry_unbind_port to be zero indexed instead of 1 indexed for port nums 
- [x] Remove PID related functions from our documentation 
- [x] Add rotation sensor rate setting function documentation 
- [x] Document IMU being an alias for Imu now 
- [x] The actual changelog itself

**Comment by HotelCalifornia** [comment]
> Document Imu being an alias for IMU now

It's the other way around

**Comment by WillXuCodes** [comment]
Mission accomplished on this
